### ISSUE TITLE
The finisher preset identified by "LogFormData" could not be found. For TYPO3 V11.

### ISSUE THREAD

**Issue by ganybhat** [pagemachine/typo3-formlog#109]
I am getting this error on TYPO3 11.

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1328709784: The finisher preset identified by "LogFormData" could not be found, or the implementationClassName was not specified. | TYPO3\CMS\Form\Domain\Model\Exception\FinisherPresetNotFoundException thrown in file /html/typo3/typo3_src-11.5.3/typo3/sysext/form/Classes/Domain/Model/FormDefinition.php in line 552.

Also the Log Form Data finisher selector in the BE form is broken.

**Comment by ganybhat** [comment]
Now got it working by adding **ext_typoscript_setup.txt** file content to "/formlog/Configuration/TypoScript/setup.typoscript".

And this code in ext_tables.php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addStaticFile(
    'formlog',
    'Configuration/TypoScript',
    'EXT:form Formlog Finisher'
);
And then select in TS template.

**Comment by mbrodala** [comment]
There is no release for TYPO3v11 yet, so issues are to be expected.

**Comment by mbrodala** [comment]
@ganybhat Can you retry? Version [2.0.0](https://github.com/pagemachine/typo3-formlog/releases/tag/2.0.0) was officially released with TYPO3v11 support.

**Comment by mbrodala** [comment]
There has been no further feedback, so I'll assume this is fixed.
