### ISSUE TITLE
Add tx_formlog_entries to TableGarbageCollectionTask

### ISSUE THREAD

**Issue by Nemo64** [pagemachine/typo3-formlog#11]
Related to #5 

It should be easily possible to automatically remove old entries from fromlog.
The most out-of-the-box way I know of would be to add it to the `TableGarbageCollectionTask`.

I'm thinking of something like this:

```PHP
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['scheduler']['tasks'][\TYPO3\CMS\Scheduler\Task\TableGarbageCollectionTask::class]['options']['tables']['tx_formlog_entries'] = [
    'dateField' => 'tstamp',
    'expirePeriod' => 90,
];
```

I'm not sure where I read it but 90 days was how long you should keep the data but also when you should delete it.

**Comment by mbrodala** [comment]
Good idea, can you add a PR for this?
