### ISSUE TITLE
Export not working on TYPO3 11

### ISSUE THREAD

**Issue by kszymukowicz** [pagemachine/typo3-formlog#129]
hi

can someone confirm (or not) that after clicking the Export button in TYPO311 there is no div shown with possibility to choose cvs/xls? I checked the console. There is no JS errors and in network all file are loaded. Tnx.

Using 2.0.0.

**Comment by mbrodala** [comment]
This is/was a known issue, see https://github.com/pagemachine/typo3-formlog/issues/122

It was fixed today and will be released soon.

**Comment by mbrodala** [comment]
This was released with version [2.0.1](https://github.com/pagemachine/typo3-formlog/releases/tag/2.0.1) now.

**Comment by kszymukowicz** [comment]
Tnx a lot!
