### ISSUE TITLE
exception after updating

### ISSUE THREAD

**Issue by ses2013** [pagemachine/typo3-formlog#134]
After updating from ver. 1 to 2 with exact the same settings I get an exception after submitting the form.

Doctrine\DBAL\Exception\NotNullConstraintViolationException

An exception occurred while executing 'INSERT INTO `tx_formlog_entries` 

 Column 'pid' cannot be null

**Comment by mbrodala** [comment]
Can you add more details, especially the TYPO3 version? And the full error trace if possible.

**Comment by mbrodala** [comment]
Thanks for the details, this confirms the issue but still does not give a hint what goes wrong here. Is there something special about the way the form is rendered/called? Is the page with the form regularly accessible?

**Comment by ses2013** [comment]
When I downgrade to 1.4.1 and run the database compare tool ist says:

DROP INDEX `parent` ON tx_formlog_entries
CREATE INDEX `parent` ON tx_formlog_entries (pid)
ALTER TABLE `tx_formlog_entries` CHANGE `deleted` `deleted` INT UNSIGNED DEFAULT 0 NOT NULL
Current value: deleted SMALLINT UNSIGNED DEFAULT 0 NOT NULL

Maybe after upgrading something went wrong with the database structure?

**Comment by ses2013** [comment]
But the page is visible and acessable. Strange!

**Comment by ses2013** [comment]
OK, sorry I close this issue:
We made an XCLASS of the extension in our site-extension which produced the error.
Sorry of the waste of time.

**Comment by mbrodala** [comment]
Thanks for the update. :-)
