### ISSUE TITLE
Feature request: add scheduler task to clear log entry older than x days

### ISSUE THREAD

**Issue by bh-teufels** [pagemachine/typo3-formlog#153]
for the European GDPR it would be helpfull if you could provide a scheduler task to remove log entry older than a given amount of days

**Comment by mbrodala** [comment]
This can be done already with TYPO3 alone, [see README](https://github.com/pagemachine/typo3-formlog/blob/dff66af510876971745b25fdc5eb847275556c68/README.md#log-entry-cleanup).
