### ISSUE TITLE
missing date fields in the data-result in DB

### ISSUE THREAD

**Issue by kurtkk** [pagemachine/typo3-formlog#154]
Form-fields like "**date**" or "**datepicker**" wouldn't be written into the database date-field!?
So it is not possible to show them nor in the list.columns neither in the export.columns.

With the Ext. "form_to_database" you'll get them in this structure (sub-array):
"datum":{"date":"2022-05-16 08:06:44.000000","timezone_type":3,"timezone":"Europe\/Berlin"} e.g.

**Comment by mbrodala** [comment]
Since [version 2.1.0](https://github.com/pagemachine/typo3-formlog/releases/tag/2.1.0) that's actually supported. By default all form values are logged, so it really depends on which columns you display in the list / export. How does your config look like exactly?

**Comment by mbrodala** [comment]
Closing for now, please report back if you have more details.
