### ISSUE TITLE
TYPO3 v12 compatibilty bug: the sys_language table is no more used

### ISSUE THREAD

**Issue by phil64** [pagemachine/typo3-formlog#178]
In TYPO3 v12, the sys_language table is no more present.
So, when asking for the detail of a log entry, this error happens.
`Field language of table tx_formlog_entries reference to foreign table sys_language, but this table is not defined in TCA`

See these changelogs: 
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.3/Deprecation-94165-SysLanguageDatabaseTable.html?highlight=sys_language
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html?highlight=sys_language

**Comment by mbrodala** [comment]
Thanks for the report! This is fixed with [version 2.2.1](https://github.com/pagemachine/typo3-formlog/releases/tag/2.2.1) now.

**Comment by phil64** [comment]
Thanks a lot !
