### ISSUE TITLE
finisherVariables working example

### ISSUE THREAD

**Issue by Treedent** [pagemachine/typo3-formlog#18]
With the poor explanation of the Readme file, I can't make finisherVariables working well.
When inserting a custom variable 'email-confirmed' in YAML form definition file, I've got the following error :

Argument 1 passed to TYPO3\CMS\Core\Utility\ArrayUtility::getValueByPath() must be of the type array, null given, called in /var/www/clients/client30/web321/typo3_src/typo3_src-8.7.19/typo3/sysext/form/Classes/Domain/Finishers/FinisherVariableProvider.php on line 100

TypeError thrown in file
/var/www/clients/client30/web321/typo3_src/typo3_src-8.7.19/typo3/sysext/core/Classes/Utility/ArrayUtility.php in line 178.

32 TYPO3\CMS\Core\Utility\ArrayUtility::getValueByPath(NULL, "email-confirmed", ".")

Could you provide a working exemple of a YAML form configuration file with implementation of custom finisher variables.
Thanks.

**Comment by mbrodala** [comment]
You cannot set finisher variables from YAML. Please see [Share data between finishers](https://docs.typo3.org/typo3cms/extensions/form/Concepts/FrontendRendering/Index.html#concepts-frontendrendering-codecomponents-customfinisherimplementations-finishercontext-sharedatabetweenfinishers) in the official documentation which explains how to add values to the `FinisherVariableProvider`.

The `finisherVariables` option of our `LogFormData` finisher only configures which variables provided by other finishers should be added to the log.

**Comment by mbrodala** [comment]
I've just added that link to the README which makes this part a bit clearer I hope.
