### ISSUE TITLE
tstamp field will be not filled (needed for TableGarbageCollectionTask)

### ISSUE THREAD

**Issue by kassor** [pagemachine/typo3-formlog#19]
Hey folks,
the loggerFinisher doesnt fill the tstamp field which is needed because the defined dateField in TableGarbageCollectionTask is tstamp

**Comment by mbrodala** [comment]
I can confirm the issue, thanks for bringing this up.

**Comment by mbrodala** [comment]
This has been fixed with [version 1.1.7](https://github.com/pagemachine/typo3-formlog/releases/tag/1.1.7), the release will show up in the TER soon.
