### ISSUE TITLE
Update to Typo3 8.7.25 failed with Classic Mode

### ISSUE THREAD

**Issue by cmaus-lus** [pagemachine/typo3-formlog#23]
After the Update from Typo3 8.7.24 to 8.7.25 the System crashed with the following Error:

```
Warning: Uncaught TYPO3\PharStreamWrapper\Exception: Executing phar:///home/www/p*****/html/updatetest/typo3conf/ext/formlog//vendors.phar/vendor/autoload.php is denied in /html/updatetest/typo3_src-8.7.25/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php:39
Stack trace:
#0 /html/updatetest/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/Behavior.php(72): TYPO3\CMS\Core\IO\PharStreamWrapperInterceptor->assert('phar:///home/ww...', 'stream_open')
#1 /html/updatetest/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/Manager.php(110): TYPO3\PharStreamWrapper\Behavior->assert('phar:///home/ww...', 'stream_open')
#2 /html/updatetest/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(421): TYPO3\PharStreamWrapper\Manager->assert('phar:///home/ww...', 'stream_open')
#3 /html/updatetest/typo3_src-8.7.25/vendor/typo3/phar-stream-wrapper/src/PharStreamWrapper.php(256): TYPO3\PharStreamWrapper\PharStreamWrapper->assert('phar:///home/ww...', 'stream_open')
#4 /html/updatetest/typo3c in /html/updatetest/typo3_src-8.7.25/typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php on line 39

Fatal error: TYPO3\CMS\Core\Utility\ExtensionManagementUtility::main(): Failed opening required 'phar:///home/www/p*****/html/updatetest/typo3conf/ext/formlog//vendors.phar/vendor/autoload.php' (include_path='.:/usr/local/pear') in /html/updatetest/typo3conf/ext/formlog/ext_localconf.php on line 17
```

**Comment by ohader** [comment]
Which PHP version is used? Is there a possibility to reproduce that behavior in a DDEV/Docker environment? This would help to debug the processing

**Comment by ohader** [comment]
Where is `vendors.phar` coming from and how is it loaded? I could not find that file in this repository...

**Comment by mbrodala** [comment]
@ohader The `vendors.phar` is built in a Travis run right before deploying to TER:

https://github.com/pagemachine/typo3-formlog/blob/73eb02238c4264070932bf25114ec5dd23e402cd/.travis.yml#L73

**Comment by cmaus-lus** [comment]
> Which PHP version is used? Is there a possibility to reproduce that behavior in a DDEV/Docker environment? This would help to debug the processing

PHP Version was 7.2.

**Comment by ohader** [comment]
I've just tested that locally with PHP 7.0.33/fcgi on macOS and TER version of the extension, but could not reproduce.
Could you please name the complete version, how it's invoked (Apache, fastcgi, ...) and which operating system or distribution has been used?

Can you please debug `typo3/sysext/core/Classes/IO/PharStreamWrapperInterceptor.php` a litte bit further? Interesting variables would be
* `$invocation`
* `$baseName`
* `PATH_site`

Thanks in advance!

**Comment by cmaus-lus** [comment]
PHP complete version is "7.2.10-latest CGI",
Apache on Linux 2.6.32-openvz-042stab127.2-amd64.

Here the debugging results:
The variables $invocation, $baseName are empty,
PATH_SITE is the path to my root directory (/home/www/p******/html/updatetest/)

**Comment by ohader** [comment]
Thx. That would mean the probably `TYPO3\PharStreamWrapper\Helper::determineBaseFile` cannot resolve the according phar file from the given `phar://...` string.

If spotted two slashes (`//`) in the string to be resolved `/home/www/p*****/html/updatetest/typo3conf/ext/formlog//vendors.phar/vendor/autoload.php`.

The according check that is executed internally is
```
$result = is_file('/home/www/p*****/html/updatetest/typo3conf/ext/formlog//vendors.phar');
```
(a `var_dump($result)` would be interesting here - in my case it works with two slashes - I guess it does not in your scenario)

**Comment by ohader** [comment]
`typo3conf/ext/formlog/ext_localconf.php` probably should look like the following (removing `/` before `vendors.phar/vendor/autoload.php`)

```
require 'phar://' . \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('formlog') . 'vendors.phar/vendor/autoload.php';
```

**Comment by ohader** [comment]
I hope it actually is fixed for @cmaus-lus

**Comment by cmaus-lus** [comment]
> I hope it actually is fixed for @cmaus-lus

Yes, with the newest Version it works. 
Thank You for your help

**Comment by mbrodala** [comment]
Yes, @ohader thanks for the fix! And thanks @cmaus-lus for the report. :-)
