### ISSUE TITLE
TYPO3 v10: AjaxBackend Action does not match  Method signature

### ISSUE THREAD

**Issue by pulponair** [pagemachine/typo3-formlog#38]
IS:
` public function searchAction(ServerRequestInterface $request, ResponseInterface $response): ResponseInterface`

Should be:
`public function searchAction(ServerRequestInterface $request): ResponseInterface`

Result:
SuggestFilter brocken.

**Comment by mbrodala** [comment]
Nice catch. Would you like to post a PR to update this? You'd need to create a custom JSON response however since `JsonResponse` is only available in [TYPO3v9 and newer](https://review.typo3.org/c/Packages/TYPO3.CMS/+/54059/).

**Comment by pulponair** [comment]
@mbrodala sure, do you want it to be backward compatible or TYPO3 v10 only?

**Comment by mbrodala** [comment]
We'd like to stay compatible to TYPO3v8 and TYPO3v9 as long as possible.

**Comment by pulponair** [comment]
@mbrodala all right. Then i ll need your hand for review since i dont have time for indeep 8 and 9 testing :).

**Comment by mbrodala** [comment]
Of course, I'll do a thorough review.

On that note it should actually be fairly easy to add a functional test for the `FormLogSuggestController` to automatically test this ...
