### ISSUE TITLE
TYPO3 v10: Remove usage of $viewFormatToObjectNameMap in Export Action 

### ISSUE THREAD

**Issue by pulponair** [pagemachine/typo3-formlog#39]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87511-RemoveViewFormatToObjectNameMapProperty.html

Export broken in TYPO3 v10:

**Comment by mbrodala** [comment]
Would you like to post a PR to fix this? We'd basically need to replicate the current logic in a new `initializeExportAction()` to prepare the desired view.

**Comment by pulponair** [comment]
@mbrodala sure.
