### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by eduardofrank** [pagemachine/typo3-formlog#4]
I have a site with a couple of existing and working forms, one of which I would like to log. Upon installing the form log extension, the existing forms don't render properly anymore and following error prompts on screen: TYPO3.CMS.Form.mixins.formElementMixins.BaseCollectionEditorsMixin does not exist within the configuration.
At this stage no form has been yet configured with the form log finisher. The extension has just been installed.
Configuring the finisher on any of the forms does not clear the error.
I'm using CMS 8.7.10.

**Comment by mbrodala** [comment]
This is fixed by 2217e5ad80b46e823f61c159b288580051a5cc5a and will be released with 1.1.1 in a few minutes. Thanks for reporting!
