### ISSUE TITLE
Problem with export on filtered data

### ISSUE THREAD

**Issue by achim1234** [pagemachine/typo3-formlog#49]
Hallo,

I have a problem with the export function on filtered log entries.
We have a site with multiple forms and we want to export the data
for each form separately. But when I try to export the filtered data,
the export file includes the data from all forms. This happens
with the CSV and Excel export.
I don't know if this is a bug or a missing feature.

If it is a bug we have following environment:
	-TYPO3 10.4.8 in composer mode
	-formlog 1.3.1

**Comment by mbrodala** [comment]
Thanks for the report. There where indeed quite some changes here for compatibility to TYPO3v10, so I'll have a look.

**Comment by mbrodala** [comment]
@achim1234 I just checked and the export works fine (both CSV and XLSX) with TYPOv10. An active page filter is respected with the export:

![image](https://user-images.githubusercontent.com/5037116/94417652-a2944600-0180-11eb-9fdc-96ee58482be5.png)
![image](https://user-images.githubusercontent.com/5037116/94417672-a9bb5400-0180-11eb-9b6f-912141026104.png)
![image](https://user-images.githubusercontent.com/5037116/94417691-afb13500-0180-11eb-9a71-97bf3a713199.png)
![image](https://user-images.githubusercontent.com/5037116/94417725-b8a20680-0180-11eb-90ba-d721c3bce6ee.png)

Can you add more details about your issue and how to reproduce?

**Comment by achim1234** [comment]
@mbrodala I found out, that the filter isn't respected on the export, when I filter the entries via the dropdown menu (screenshot). All entries get exported:
![dropdown-filter](https://user-images.githubusercontent.com/11617556/94529281-d4b5ae80-0239-11eb-97f8-959b6f73ae52.png)


When I press the filter button on the single entry (screenshot 2) the export works fine:
![filter](https://user-images.githubusercontent.com/11617556/94529303-dc755300-0239-11eb-8663-c6b5d107b1d4.png)

**Comment by mbrodala** [comment]
@achim1234 Yes, I can reproduce the problem this way, thanks!

**Comment by mbrodala** [comment]
A fix for this has been released with version 1.3.2 now, thanks for the report!
