### ISSUE TITLE
type: FileUpload is not saved at all

### ISSUE THREAD

**Issue by chwessalowski** [pagemachine/typo3-formlog#53]
Thanks a lot for this very cool extension. Very clever implementation.
But type: FileUpload is not saved in the JSON. Or am I doing something wrong?

**Comment by mbrodala** [comment]
What exactly do you expect to show up in the logged data? An uploaded file contains a lot of data (UID, filename, path, etc.) but without any additional processing we can store only a single plain value.

**Comment by chwessalowski** [comment]
Hello Mathias
thanks for the quick respond. 
Just the filename would do. Simple as that.
The path is in the form definition. Don't need that.

**Comment by mbrodala** [comment]
Would you try to give this a spin? I currently don't really have the time to take care of this but agree that it could be useful.
