### ISSUE TITLE
TYPO3 v11 compatibillity

### ISSUE THREAD

**Issue by pulponair** [pagemachine/typo3-formlog#83]
Bring TYPO3 v11 compatibility.

**Comment by mbrodala** [comment]
This is definitely on the roadmap but have you tried already? Did you encounter any issues?

Without a community PR this will be done as early as TYPO3v11 is released as final LTS version.

**Comment by pulponair** [comment]
@mbrodala i am about to file a PR. I did that locally, tested and it works. Stay tuned

**Comment by pulponair** [comment]
@mbrodala here we go. Would you mind having a look?

**Comment by mbrodala** [comment]
I will, soon. ;-)
