### ISSUE TITLE
fields like "date" or "date_picker" would not be displayed in the BE-list!?

### ISSUE THREAD

**Issue by kurtkk** [pagemachine/typo3-formlog#86]
I have a date-field in a form.
I put this field (beside others) into the list and export view:
```
module.tx_formlog {
    list.columns {
      100 {
         property = data.name
         label = Name
      }
      105 {
         property = data.telephone
         label = Telefon-Nr.
      }
      110 {
         property = data.email
         label = E-Mail
      }
      115 {
         property = **data.datum**
         label = Datum
      }
    }
```
Field nr. 115 will always be empty in the list and also in the detail-view!?

**Comment by mbrodala** [comment]
There is ongoing work in https://github.com/pagemachine/typo3-formlog/pull/63 to fix this. Contributions are welcome.

**Comment by mbrodala** [comment]
This has been fixed by now, see the mentioned issue.
